default_language_version:
  python: python3.12

exclude: app/api_services/graphql_service

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.28
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff-format
      - id: ruff

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: end-of-file-fixer
      - id: check-added-large-files
