[project]
name = "kkt-checker"
version = "0.1.0"
description = "Check the validity of the KKT"
requires-python = ">=3.13"

dependencies = [
    "httpx>=0.28.1",
    "mypy>=1.17.1",
    "openpyxl>=3.1.5",
    "ruff>=0.12.1",
    "aiogram>=3.22.0",
    "python-dotenv>=1.1.1",
    "aiofiles>=24.1.0",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["I", "PTH", "B", "A", "N", "PT", "COM", "E", "W", "UP"]
ignore = ["E501", "COM812"]

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true
